on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:
  on_push_main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Push event on main
        run: echo "Push event detected on main branch"

  on_pr_target_merged_to_default:
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - name: PR merged into default branch
        run: echo "The PR was merged into the default branch"
